# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ILX_translator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ILX_translator_window(object):
    def setupUi(self, ILX_translator_window):
        ILX_translator_window.setObjectName("ILX_translator_window")
        ILX_translator_window.resize(952, 722)
        ILX_translator_window.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(9)
        ILX_translator_window.setFont(font)
        ILX_translator_window.setWindowOpacity(1.0)
        ILX_translator_window.setAutoFillBackground(False)
        ILX_translator_window.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(255, 255, 255); /*White*/\n"
"}\n"
"QWidget#centralwidget{\n"
"    background-color: rgb(255, 255, 255); /*White*/\n"
"}\n"
"QMenu, QMenuBar {\n"
"    width: 200px;\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #e4e4e4, stop:1#ffde9b); /*LightGray top - Gold bottom*/\n"
"}\n"
"QMenu::item, QMenuBar::item {\n"
"    width: 200px;\n"
"    spacing: 3px;           \n"
"    padding: 2px 10px;\n"
"    background-color:  #C2C7CB; /*Dark Grey*/\n"
"    color: rgb(0,0,0);   /*Text = Black */\n"
"    border-radius: 5px;\n"
"}\n"
"QMenu::item::selected, QMenuBar::item::selected {    \n"
"    background-color:  #ffde9b; /*Gold*/\n"
"}\n"
"QMenu::item::pressed, QMenuBar::item::pressed {\n"
"    background: #ffde9b; /*Gold*/\n"
"}\n"
"QWidget#tab_translations, QWidget#tab_html{\n"
"    background-color:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0.2 #ffffff, stop: 0.5 #ffde9b, /*White top - Gold mid*/\n"
"                                stop: 0.5 #ffde9b, stop: 0.8 #ffffff); /*Gold mid - White bottom*/\n"
"}\n"
"QToolBox::tab{\n"
"    background-color: #e4e4e4; /*LightGray*/\n"
"}\n"
"QWidget#page_eng_html, QWidget#page_eng_rich_text, QWidget#page_trans_html, QWidget#page_trans_rich_text, QWidget#scrollAreaWidgetContents {\n"
"    background-color: rgb(255, 255, 255); /*White*/\n"
"}\n"
"QToolBox::tab::hover, QToolBox::tab::selected{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ffde9b, stop:0.5 rgba(255, 255, 255, 255)); /*Gold left - White right*/\n"
"}\n"
"QToolBox::tab:selected {\n"
"    border-top : 2px solid;\n"
"    border-color: #C2C7CB; /*DarkGray*/\n"
"}\n"
"QToolBox::tab::hover {\n"
"    border : 2px solid;\n"
"    border-color: #C2C7CB; /*DarkGray*/\n"
"}\n"
"QGroupBox{\n"
"background-color: #e4e4e4; /*LightGray*/\n"
"}\n"
"QTextEdit{\n"
"background-color: #e4e4e4; /*LightGray*/\n"
"}\n"
"QLineEdit{\n"
"    background-color: rgb(255, 255, 255); /*White*/\n"
"}\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid #C2C7CB; /*DarkGray*/\n"
"    position: absolute;\n"
"    top: -0.5em;\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 2px solid #C4C4C3;\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 120ex;\n"
"    padding: 7px;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #ffde9b,\n"
"                                stop: 0.5 #ffde9b, stop: 1.0 #fafafa);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color:#ffde9b; /* same as pane color */\n"
"}\n"
"\n"
" QPushButton::hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"QPushButton::pressed {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.1 #f4f4f4,\n"
"                                stop: 0.9 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 2px solid #C4C4C3;\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"    border-radius: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ILX_translator_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_tab_and_buttons = QtWidgets.QVBoxLayout()
        self.verticalLayout_tab_and_buttons.setObjectName("verticalLayout_tab_and_buttons")
        self.groupBox_notification_template = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_notification_template.setFont(font)
        self.groupBox_notification_template.setObjectName("groupBox_notification_template")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_notification_template)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_notification_template = QtWidgets.QLineEdit(self.groupBox_notification_template)
        self.lineEdit_notification_template.setFrame(True)
        self.lineEdit_notification_template.setObjectName("lineEdit_notification_template")
        self.gridLayout_2.addWidget(self.lineEdit_notification_template, 0, 0, 1, 1)
        self.verticalLayout_tab_and_buttons.addWidget(self.groupBox_notification_template)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_translations = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_translations.sizePolicy().hasHeightForWidth())
        self.tab_translations.setSizePolicy(sizePolicy)
        self.tab_translations.setObjectName("tab_translations")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_translations)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_translation_lineEdits = QtWidgets.QScrollArea(self.tab_translations)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_translation_lineEdits.sizePolicy().hasHeightForWidth())
        self.scrollArea_translation_lineEdits.setSizePolicy(sizePolicy)
        self.scrollArea_translation_lineEdits.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_translation_lineEdits.setWidgetResizable(True)
        self.scrollArea_translation_lineEdits.setObjectName("scrollArea_translation_lineEdits")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 912, 453))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_translations = QtWidgets.QHBoxLayout()
        self.horizontalLayout_translations.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_translations.setObjectName("horizontalLayout_translations")
        self.groupBox_eng_values = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_eng_values.sizePolicy().hasHeightForWidth())
        self.groupBox_eng_values.setSizePolicy(sizePolicy)
        self.groupBox_eng_values.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_eng_values.setFont(font)
        self.groupBox_eng_values.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groupBox_eng_values.setObjectName("groupBox_eng_values")
        self.horizontalLayout_translations.addWidget(self.groupBox_eng_values)
        self.groupBox_trans_values = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_trans_values.sizePolicy().hasHeightForWidth())
        self.groupBox_trans_values.setSizePolicy(sizePolicy)
        self.groupBox_trans_values.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_trans_values.setFont(font)
        self.groupBox_trans_values.setObjectName("groupBox_trans_values")
        self.horizontalLayout_translations.addWidget(self.groupBox_trans_values)
        self.gridLayout_3.addLayout(self.horizontalLayout_translations, 0, 0, 1, 1)
        self.scrollArea_translation_lineEdits.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea_translation_lineEdits, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_translations, "")
        self.tab_html = QtWidgets.QWidget()
        self.tab_html.setObjectName("tab_html")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_html)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox_eng = QtWidgets.QToolBox(self.tab_html)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_eng.sizePolicy().hasHeightForWidth())
        self.toolBox_eng.setSizePolicy(sizePolicy)
        self.toolBox_eng.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(9)
        self.toolBox_eng.setFont(font)
        self.toolBox_eng.setStyleSheet("")
        self.toolBox_eng.setObjectName("toolBox_eng")
        self.page_eng_html = QtWidgets.QWidget()
        self.page_eng_html.setGeometry(QtCore.QRect(0, 0, 453, 393))
        self.page_eng_html.setObjectName("page_eng_html")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_eng_html)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_search_eng = QtWidgets.QLineEdit(self.page_eng_html)
        self.lineEdit_search_eng.setObjectName("lineEdit_search_eng")
        self.gridLayout_6.addWidget(self.lineEdit_search_eng, 0, 0, 1, 1)
        self.textEdit_eng = QtWidgets.QTextEdit(self.page_eng_html)
        self.textEdit_eng.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit_eng.setObjectName("textEdit_eng")
        self.gridLayout_6.addWidget(self.textEdit_eng, 1, 0, 1, 1)
        self.toolBox_eng.addItem(self.page_eng_html, "")
        self.page_eng_rich_text = QtWidgets.QWidget()
        self.page_eng_rich_text.setGeometry(QtCore.QRect(0, 0, 453, 393))
        self.page_eng_rich_text.setObjectName("page_eng_rich_text")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_eng_rich_text)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.textEdit_eng_rich_text = QtWidgets.QTextEdit(self.page_eng_rich_text)
        self.textEdit_eng_rich_text.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit_eng_rich_text.setReadOnly(True)
        self.textEdit_eng_rich_text.setObjectName("textEdit_eng_rich_text")
        self.gridLayout_9.addWidget(self.textEdit_eng_rich_text, 0, 0, 1, 1)
        self.toolBox_eng.addItem(self.page_eng_rich_text, "")
        self.horizontalLayout.addWidget(self.toolBox_eng)
        self.toolBox_trans = QtWidgets.QToolBox(self.tab_html)
        self.toolBox_trans.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(9)
        self.toolBox_trans.setFont(font)
        self.toolBox_trans.setStyleSheet("")
        self.toolBox_trans.setObjectName("toolBox_trans")
        self.page_trans_html = QtWidgets.QWidget()
        self.page_trans_html.setGeometry(QtCore.QRect(0, 0, 453, 393))
        self.page_trans_html.setObjectName("page_trans_html")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_trans_html)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_search_trans = QtWidgets.QLineEdit(self.page_trans_html)
        self.lineEdit_search_trans.setObjectName("lineEdit_search_trans")
        self.gridLayout_7.addWidget(self.lineEdit_search_trans, 0, 0, 1, 1)
        self.textEdit_trans = QtWidgets.QTextEdit(self.page_trans_html)
        self.textEdit_trans.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit_trans.setObjectName("textEdit_trans")
        self.gridLayout_7.addWidget(self.textEdit_trans, 1, 0, 1, 1)
        self.toolBox_trans.addItem(self.page_trans_html, "")
        self.page_trans_rich_text = QtWidgets.QWidget()
        self.page_trans_rich_text.setGeometry(QtCore.QRect(0, 0, 453, 393))
        self.page_trans_rich_text.setObjectName("page_trans_rich_text")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_trans_rich_text)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.textEdit_trans_rich_text = QtWidgets.QTextEdit(self.page_trans_rich_text)
        self.textEdit_trans_rich_text.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit_trans_rich_text.setReadOnly(True)
        self.textEdit_trans_rich_text.setObjectName("textEdit_trans_rich_text")
        self.gridLayout_8.addWidget(self.textEdit_trans_rich_text, 0, 0, 1, 1)
        self.toolBox_trans.addItem(self.page_trans_rich_text, "")
        self.horizontalLayout.addWidget(self.toolBox_trans)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_html, "")
        self.verticalLayout_tab_and_buttons.addWidget(self.tabWidget)
        self.horizontalLayout_export_import_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_export_import_buttons.setObjectName("horizontalLayout_export_import_buttons")
        self.pushButton_export = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_export.setFont(font)
        self.pushButton_export.setObjectName("pushButton_export")
        self.horizontalLayout_export_import_buttons.addWidget(self.pushButton_export)
        self.pushButton_import = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_import.setFont(font)
        self.pushButton_import.setObjectName("pushButton_import")
        self.horizontalLayout_export_import_buttons.addWidget(self.pushButton_import)
        self.verticalLayout_tab_and_buttons.addLayout(self.horizontalLayout_export_import_buttons)
        self.pushButton_generate = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_generate.setFont(font)
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.verticalLayout_tab_and_buttons.addWidget(self.pushButton_generate)
        self.gridLayout_4.addLayout(self.verticalLayout_tab_and_buttons, 0, 0, 1, 1)
        ILX_translator_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ILX_translator_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 20))
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setMinimumSize(QtCore.QSize(0, 0))
        self.menuFile.setObjectName("menuFile")
        ILX_translator_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ILX_translator_window)
        self.statusbar.setObjectName("statusbar")
        ILX_translator_window.setStatusBar(self.statusbar)
        self.actionSave_html = QtWidgets.QAction(ILX_translator_window)
        self.actionSave_html.setObjectName("actionSave_html")
        self.actionImport_html = QtWidgets.QAction(ILX_translator_window)
        self.actionImport_html.setObjectName("actionImport_html")
        self.menuFile.addAction(self.actionSave_html)
        self.menuFile.addAction(self.actionImport_html)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ILX_translator_window)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox_eng.setCurrentIndex(0)
        self.toolBox_trans.setCurrentIndex(0)
        self.textEdit_eng.textChanged.connect(ILX_translator_window.textEdit_html_eng_changed) # type: ignore
        self.pushButton_generate.clicked.connect(ILX_translator_window.button_clicked_generate) # type: ignore
        self.textEdit_trans.textChanged.connect(ILX_translator_window.textEdit_html_trans_changed) # type: ignore
        self.pushButton_export.clicked.connect(ILX_translator_window.button_clicked_export) # type: ignore
        self.pushButton_import.clicked.connect(ILX_translator_window.button_clicked_import) # type: ignore
        self.lineEdit_search_eng.textChanged['QString'].connect(ILX_translator_window.lineEdit_search_eng_changed) # type: ignore
        self.lineEdit_search_trans.textChanged['QString'].connect(ILX_translator_window.lineEdit_search_trans_changed) # type: ignore
        self.actionSave_html.triggered.connect(ILX_translator_window.Save_html_triggered) # type: ignore
        self.actionImport_html.triggered.connect(ILX_translator_window.Import_html_triggered) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ILX_translator_window)

    def retranslateUi(self, ILX_translator_window):
        _translate = QtCore.QCoreApplication.translate
        ILX_translator_window.setWindowTitle(_translate("ILX_translator_window", "ILX html Replacer"))
        self.groupBox_notification_template.setTitle(_translate("ILX_translator_window", "Notification Template:"))
        self.lineEdit_notification_template.setText(_translate("ILX_translator_window", "Unspecified_notification_template"))
        self.groupBox_eng_values.setTitle(_translate("ILX_translator_window", "English"))
        self.groupBox_trans_values.setTitle(_translate("ILX_translator_window", "Translation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_translations), _translate("ILX_translator_window", "Translations"))
        self.lineEdit_search_eng.setPlaceholderText(_translate("ILX_translator_window", "Search..."))
        self.toolBox_eng.setItemText(self.toolBox_eng.indexOf(self.page_eng_html), _translate("ILX_translator_window", "HTML English"))
        self.toolBox_eng.setItemText(self.toolBox_eng.indexOf(self.page_eng_rich_text), _translate("ILX_translator_window", "Rich Text - English"))
        self.lineEdit_search_trans.setPlaceholderText(_translate("ILX_translator_window", "Search...."))
        self.toolBox_trans.setItemText(self.toolBox_trans.indexOf(self.page_trans_html), _translate("ILX_translator_window", "HTML Translated"))
        self.toolBox_trans.setItemText(self.toolBox_trans.indexOf(self.page_trans_rich_text), _translate("ILX_translator_window", "Rich Text - Translated"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_html), _translate("ILX_translator_window", "HTML replacer"))
        self.pushButton_export.setText(_translate("ILX_translator_window", "Export\n"
"Translation\n"
"Template"))
        self.pushButton_import.setText(_translate("ILX_translator_window", "Import\n"
"Translation\n"
"Template"))
        self.pushButton_generate.setText(_translate("ILX_translator_window", "Generate\n"
"HTML"))
        self.menuFile.setTitle(_translate("ILX_translator_window", "File"))
        self.actionSave_html.setText(_translate("ILX_translator_window", "Save English html"))
        self.actionImport_html.setText(_translate("ILX_translator_window", "Import English html"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ILX_translator_window = QtWidgets.QMainWindow()
    ui = Ui_ILX_translator_window()
    ui.setupUi(ILX_translator_window)
    ILX_translator_window.show()
    sys.exit(app.exec_())
